<?php
require_once('newai_executesql.php');
require_once('newai_export.php');
require_once('newai_filelist.php');
require_once('newai_import.php');
require_once('newai_init.php');
require_once('newai_listone.php');
require_once('newai_batchedit.php');
require_once('newai_listtwo.php');
require_once('newai_report.php');
require_once('newai_sql.php');
require_once('newai_tree.php');
require_once('newai_view.php');
require_once('newai_license.php');
require_once('newai_search.php');
require_once('newai_message.php');
?>